import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import tinycolor from 'tinycolor2';

// Evaluate the pinned Readest definitions with its own color library. Only
// static built-in palette data ships to ArkTS/ArkWeb; no custom-theme editor.
const result = await build({
  stdin: { contents: "export { themes, themeVariables } from './vendor/readest/apps/readest-app/src/styles/themes.ts';", resolveDir: process.cwd() },
  bundle: true, write: false, platform: 'node', format: 'esm'
});
const { themes, themeVariables } = await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const args = (p, scheme) => [p['base-100'], p['base-content'], p['base-200'], p['base-300'],
  tinycolor.mix(p['base-100'], p['base-content'], 65).toHexString(), p.primary, themeVariables(p, scheme)['--color-primary-content']].map(v => JSON.stringify(v)).join(', ');
const source = `// Generated by scripts/generate-themes.mjs from pinned Readest themes.ts.
// Readest copyright holders, AGPL-3.0-or-later. Do not edit palette values here.
export class ThemePalette {
  bg: string; fg: string; inset: string; line: string; muted: string; primary: string; primaryText: string;
  constructor(bg: string, fg: string, inset: string, line: string, muted: string, primary: string, primaryText: string) {
    this.bg = bg; this.fg = fg; this.inset = inset; this.line = line; this.muted = muted; this.primary = primary; this.primaryText = primaryText;
  }
}
export class ThemeDefinition {
  name: string; label: string; light: ThemePalette; dark: ThemePalette;
  constructor(name: string, label: string, light: ThemePalette, dark: ThemePalette) {
    this.name = name; this.label = label; this.light = light; this.dark = dark;
  }
}
export const BUILTIN_THEMES: ThemeDefinition[] = [
${themes.map(t => `  new ThemeDefinition(${JSON.stringify(t.name)}, ${JSON.stringify(t.label)}, new ThemePalette(${args(t.colors.light, 'light')}), new ThemePalette(${args(t.colors.dark, 'dark')}))`).join(',\n')}
];
export function isThemeColor(name: string): boolean { return BUILTIN_THEMES.some((theme: ThemeDefinition) => theme.name === name); }
export function themePalette(name: string, dark: boolean): ThemePalette {
  const theme = BUILTIN_THEMES.find((item: ThemeDefinition) => item.name === name) || BUILTIN_THEMES[0];
  return dark ? theme.dark : theme.light;
}
export function isThemeMode(mode: string): boolean { return ['auto', 'light', 'dark'].includes(mode); }
export function themeIsDark(mode: string, systemDark: boolean): boolean { return mode === 'dark' || (mode === 'auto' && systemDark); }
`;
await writeFile('entry/src/main/ets/core/Themes.ets', source);
