import { mkdir, writeFile } from 'node:fs/promises';
const strings = {
  book_actions: ['Book actions', '书籍操作'], details: ['Details', '详情'], book_details: ['Book Details', '书籍详情'],
  share: ['Share', '分享'], share_book: ['Share Book', '分享书籍'], delete: ['Delete', '删除'],
  filename: ['File Name', '文件名'], publisher: ['Publisher', '出版社'], book_language: ['Language', '语言'],
  published: ['Published', '出版日期'], identifier: ['Identifier', '标识符'], imported_on: ['Imported', '导入日期'],
  description: ['Description', '简介'], no_description: ['No description available.', '暂无简介。'],
  metadata: ['Metadata', '书籍信息'], format: ['Format', '格式'], unknown: ['Unknown', '未知'],
  add_bookmark: ['Add Bookmark', '添加书签'], remove_bookmark: ['Remove Bookmark', '移除书签'],
  bookmarks: ['Bookmarks', '书签'], annotations: ['Annotations', '标注'], highlights: ['Highlights', '高亮'],
  highlight_hint: ['Select text in the book to highlight it.', '选中书中的文字即可添加高亮。'],
  empty_bookmarks: ['No bookmarks yet.', '还没有书签。'], empty_highlights: ['No highlights yet.', '还没有高亮。'],
  highlight_yellow: ['Yellow', '黄色'], highlight_green: ['Green', '绿色'], highlight_blue: ['Blue', '蓝色'],
  highlight_pink: ['Pink', '粉色'], highlight_purple: ['Purple', '紫色'],
  module_desc: ['Offline EPUB reading with bookmarks, highlights, custom typography and cloud sync', '离线 EPUB 阅读，支持书签、高亮、自定义排版与云同步'], EntryAbility_desc: ['Read EPUB books offline and sync your library and reading progress', '离线阅读 EPUB 电子书，同步书架与阅读进度'], EntryAbility_label: ['Readest', 'Readest'],
  library_subtitle: ['Your books, at your own pace.', '随时翻开，自在阅读。'], library: ['Bookshelf', '书架'], books: ['books', '本书'], import: ['Import EPUB', '导入 EPUB'],
  settings: ['Settings', '设置'], importing: ['Importing and checking EPUB…', '正在导入并检查 EPUB…'], empty_title: ['Your library is empty', '书架还是空的'],
  app_language: ['App language', '应用语言'], language_system: ['System', '跟随系统'],
  empty_description: ['Add books from your device to start reading. No internet connection required.', '从设备添加书籍，即可开始阅读。无需网络连接。'],
  import_first: ['Import your first book', '导入第一本书'], unknown_author: ['Unknown author', '未知作者'], offline_footer: ['Offline reading · EPUB · Cloud sync', '离线阅读 · EPUB · 云同步'],
  kosync_title: ['KOReader Sync', 'KOReader 同步'],
  cloud_sync: ['Cloud Sync', '云同步'], readest_cloud: ['Readest Cloud', 'Readest 云端'],
  sync_on: ['On', '已启用'], sync_off: ['Paused', '已暂停'],
  always_latest: ['Always use latest', '始终采用最新位置'], send_only: ['Send only', '仅发送'], receive_only: ['Receive only', '仅接收'],
  send_metadata: ['Send Document Metadata', '发送书籍信息'],
  custom_headers: ['Custom Headers (optional)', '自定义请求头（可选）'],
  create_account: ['Create account', '创建账号'], open_book_to_sync: ['Open a book to check or send its reading position.', '打开书籍后即可检查或同步其阅读位置。'],
  error_invalid_headers: ['Check the header format. Use one Header-Name: value per line; authentication headers are managed by the app.', '请检查请求头格式，每行填写一个 Header-Name: value；认证请求头由应用管理。'],
  error_account_exists: ['This account already exists. Connect with its password.', '该账号已存在，请使用密码连接。'],
  error_annotations_limit: ['This book exceeds the supported limit of 2,000 annotations.', '此书超出了 2000 条标注的支持上限。'],
  reading_sync: ['Reading Sync', '阅读同步'], connected_as: ['Connected as {account}', '已连接账号：{account}'],
  not_connected: ['Not connected', '未连接'], sync_paused: ['Sync paused', '同步已暂停'],
  sync_strategy: ['Sync Strategy', '同步策略'], ask_on_conflict: ['Ask on conflict', '冲突时询问'],
  expand: ['Expand', '展开'], collapse: ['Collapse', '收起'],
  server_url: ['Server URL (HTTPS)', '服务器地址（HTTPS）'], username: ['Username', '用户名'], password: ['Password', '密码'], password_unchanged: ['Leave empty to keep saved password', '留空以保留已保存的密码'],
  device_name: ['Device name', '设备名称'], auto_sync: ['Enable progress sync', '启用进度同步'], newer_wins: ['The newer position wins. Missing or tied timestamps require a choice. Keep device clocks accurate.', '默认采用时间较新的位置。时间缺失或相同时会询问保留哪一个，请保持设备时间准确。'],
  connect_save: ['Connect', '连接'], sync_status: ['Sync status', '同步状态'], disconnect: ['Disconnect', '断开连接'],
  appearance: ['Reading appearance', '阅读样式'], font_size: ['Font size', '字号'], line_height: ['Line spacing', '行距'], theme_light: ['Light', '浅色'], theme_sepia: ['Sepia', '护眼'], theme_dark: ['Dark', '深色'],
  theme_system: ['System', '跟随系统'], theme_mode: ['Theme Mode', '主题模式'], theme_color: ['Theme Color', '主题颜色'], theme_reader: ['Reader', '阅读器'],
  scheme_default: ['Default', '默认'], scheme_gray: ['Gray', '灰色'], scheme_sepia: ['Sepia', '褐色'], scheme_grass: ['Grass', '草绿'],
  scheme_cherry: ['Cherry', '樱桃'], scheme_sky: ['Sky', '天空'], scheme_solarized: ['Solarized', 'Solarized'], scheme_gruvbox: ['Gruvbox', 'Gruvbox'],
  scheme_nord: ['Nord', 'Nord'], scheme_contrast: ['Contrast', '高对比度'], scheme_sunset: ['Sunset', '日落'],
  about_description: ["Readest for HarmonyOS is an independent EPUB reader for phones and tablets, with offline reading, a personal bookshelf, bookmarks and highlights, customizable typography and themes, Readest cloud sync, and KOReader progress sync.","Readest 鸿蒙版是一款面向手机和平板的独立 EPUB 阅读器，支持离线阅读、书架管理、书签与高亮、字体排版与主题设置、Readest 云同步及 KOReader 阅读进度同步。"],
  about_author: ['Developed by TenofHearts', '开发者：TenofHearts'],
  about_github: ['GitHub', 'GitHub'], about_homepage: ['Homepage', '个人主页'],
  about_independent: ['An independent project, not an official Readest release.', '本项目为独立开发，非 Readest 官方发行版。'],
  about_version: ['Version 0.0.11 · HarmonyOS', '版本 0.0.11 · HarmonyOS'], about_license: ['Licensed under AGPL-3.0-or-later', '遵循 AGPL-3.0-or-later 开源许可'],
  contents: ['Contents', '目录'], reading: ['Reading', '阅读中'], sync_now: ['Send progress', '发送进度'], check_remote: ['Check remote', '检查远端'], conflict_title: ['Choose a reading position', '选择阅读位置'],
  conflict_description: ['Reading progress differs between devices. Choose where to continue; automatic uploads are paused until you choose.', '设备之间的阅读位置不同。请选择要继续阅读的位置，自动上传已暂停。'], local: ['This device', '此设备'], remote: ['Other device', '其他设备'], keep_local: ['Continue here', '在此继续'], use_remote: ['Use other position', '采用另一位置'],
  remove_description: ['Remove this book and its local reading data?', '移除此书和本地阅读记录？'], cancel: ['Cancel', '取消'], remove: ['Remove', '移除'],
  status_idle: ['Offline ready', '离线就绪'], status_connected: ['Connected', '已连接'], status_checking: ['Checking progress…', '正在检查进度…'], status_conflict: ['Choose a position', '请选择位置'], status_synced: ['Progress synced', '进度已同步'], status_pending: ['Progress saved locally', '进度已保存到本地'], status_error: ['Sync needs attention', '同步需处理'],
  error_auth_failed: ['Check your username and password.', '请检查用户名和密码。'], error_https_required: ['Enter a valid HTTPS server URL.', '请输入有效的 HTTPS 服务器地址。'], error_not_kosync: ['This URL did not return a KoSync JSON response.', '该地址未返回 KoSync JSON 响应。'],
  error_credentials_required: ['Enter a username and password.', '请输入用户名和密码。'], error_credentials_unavailable: ['Saved credentials could not be decrypted. Connect again.', '无法解密已保存的凭据，请重新连接。'], error_duplicate_book: ['This EPUB is already in your library.', '此 EPUB 已在书架中。'],
  error_invalid_epub: ['This file is not a valid EPUB.', '该文件不是有效的 EPUB。'], error_drm_or_encrypted: ['Encrypted or DRM-protected EPUBs are not supported.', '暂不支持加密或受 DRM 保护的 EPUB。'], error_fixed_layout_unsupported: ['Fixed-layout EPUBs are not supported in this release.', '此版本暂不支持固定布局的 EPUB。'],
  error_book_too_large: ['The book is empty or exceeds the supported size (128 MB compressed / 512 MB expanded).', '书籍为空或超过支持大小（压缩后 128 MB / 解压后 512 MB）。'],
  error_unresolved_position: ['The server position could not be restored. Automatic upload is paused. Check that both apps use the same EPUB, then retry syncing.', '无法恢复服务器位置，已暂停自动上传。请检查两端是否使用相同 EPUB，然后重试同步。'],
  error_network_timeout: ['The sync server did not respond in time. Check the tablet network, VPN or Wi-Fi proxy, then retry.', '连接同步服务器超时。请检查平板网络、VPN 或 Wi-Fi 代理后重试。'],
  error_network_dns: ['The sync server address could not be resolved. Check the server URL and network DNS.', '无法解析同步服务器地址。请检查服务器地址和网络 DNS。'],
  error_network_tls: ['A secure connection to the sync server could not be verified. Check the device clock and server certificate.', '无法验证与同步服务器的安全连接。请检查设备时间和服务器证书。'],
  error_network_error: ['The sync server could not be reached. Check the network, VPN or Wi-Fi proxy, then retry.', '无法连接同步服务器。请检查网络、VPN 或 Wi-Fi 代理后重试。'],
  error_import_timeout: ['Reading this EPUB took too long. Select the file again.', '读取 EPUB 超时，请重新选择文件。'], error_reader_timeout: ['The book could not be opened in time. Try opening it again.', '打开书籍超时，请重新打开。'], error_server_error: ['The sync server returned an error. Retry later.', '同步服务器返回错误，请稍后重试。'], error_invalid_progress: ['The server returned an invalid reading position.', '服务器返回的阅读位置无效。'],
  error_generic: ['The operation could not be completed. Please try again. Your saved reading data is retained.', '操作未能完成，请重试。已保存的阅读记录仍然保留。'],
  search_books: ['Search Books…', '搜索书籍…'], clear_search: ['Clear search', '清除搜索'], dismiss: ['Dismiss', '关闭'],
  view_options: ['View', '显示'], view_grid: ['Grid', '网格'], view_list: ['List', '列表'], sort_recent: ['Recently opened', '最近阅读'], sort_title: ['Title', '书名'],
  no_results: ['No matching books', '没有找到匹配的书籍'], font_layout: ['Font & Layout', '字体与布局'], theme: ['Theme', '主题'], integrations: ['Sync', '同步'], about: ['About', '关于'],
  preview: ['PREVIEW', '预览'], preview_text: ['A book is a dream that you hold in your hands.', '书是握在手中的梦。翻开一页，走进另一个世界。'],
  decrease_font: ['Decrease font size', '减小字号'], increase_font: ['Increase font size', '增大字号'], opening: ['Opening book…', '正在打开书籍…'],
  add_book: ['Add a book', '添加书籍'], reading_progress: ['Reading progress', '阅读进度'],
  previous_page: ['Previous page', '上一页'], next_page: ['Next page', '下一页'], previous_section: ['Previous section', '上一章节'], next_section: ['Next section', '下一章节'],
  go_back: ['Go back', '后退'], go_forward: ['Go forward', '前进'],
  reference: ['Reference', '参考注释'], reference_error: ['Unable to load this reference.', '无法加载此参考注释。'],
  reference_jump: ['Jump to Location', '跳转到位置'],
  error_import_read_failed: ['The EPUB could not be read from your device. Select the file again.', '无法读取设备上的 EPUB 文件，请重新选择文件。'],
  error_import_write_failed: ['The EPUB could not be saved. Check available device storage.', '无法保存 EPUB 文件，请检查设备存储空间。'],
  error_book_not_found: ['The local book file could not be found. Import the EPUB again.', '找不到本地书籍文件，请重新导入 EPUB。'],
  connecting: ['Connecting…', '正在连接…'],
  fonts: ['Fonts', '字体'], layout: ['Layout', '排版'],
  override_book_font: ['Override Book Font', '覆盖书籍字体'],
  default_font_size: ['Default Font Size', '默认字号'], minimum_font_size: ['Minimum Font Size', '最小字号'],
  font_weight: ['Font Weight', '字重'], preferred_font: ['Preferred Font', '首选字体'], font_category: ['Font Category', '字体类别'],
  serif_font: ['Serif Font', '衬线字体'], sans_serif_font: ['Sans-Serif Font', '无衬线字体'],
  monospace_font: ['Monospace Font', '等宽字体'], cjk_font: ['CJK Font', '中日韩字体'], book_font: ['Use Book Font', '使用书籍字体'],
  custom_fonts: ['Custom Fonts', '自定义字体'], manage_fonts: ['Manage Fonts', '管理字体'], add_fonts: ['Add Fonts', '添加字体'],
  font_formats: ['TrueType (.ttf) and OpenType (.otf), up to 32 MB per file.', '支持 TrueType (.ttf) 和 OpenType (.otf)，每个文件最大 32 MB。'],
  remove_font: ['Remove font', '移除字体'],
  remove_font_description: ['Remove this font? With font syncing enabled, it will also be removed from your Readest account.', '移除此字体？开启字体同步时，也会从你的 Readest 账户中移除。'],
  reading_mode: ['Reading Mode', '阅读模式'], scrolled_mode: ['Scrolled Mode', '滚动阅读'], paragraph: ['Paragraph', '段落'],
  use_book_layout: ['Use Book Layout', '使用书籍排版'], paragraph_margin: ['Paragraph Margin', '段落间距'],
  word_spacing: ['Word Spacing (px)', '词间距（像素）'], letter_spacing: ['Letter Spacing (px)', '字间距（像素）'],
  text_indent: ['Text Indent (em)', '首行缩进（em）'], full_justification: ['Full Justification', '两端对齐'], hyphenation: ['Hyphenation', '自动断词'],
  page: ['Page', '页面'], top_margin: ['Top Margin (px)', '上边距（像素）'], bottom_margin: ['Bottom Margin (px)', '下边距（像素）'],
  left_margin: ['Left Margin (px)', '左边距（像素）'], right_margin: ['Right Margin (px)', '右边距（像素）'],
  additional_margin: ['Additional Margin (%)', '附加边距（%）'], column_gap: ['Column Gap (px)', '栏间距（像素）'],
  max_columns: ['Maximum Number of Columns', '最大栏数'], max_column_width: ['Maximum Column Width (px)', '最大栏宽（像素）'],
  max_column_height: ['Maximum Column Height (px)', '最大栏高（像素）'],
  replica_syncing: ['Replica Syncing', '副本同步'], readest_replica_sync: ['Readest', 'Readest'],
  enable_replica_sync: ['Enable Sync', '启用同步'], sync_replica_now: ['Sync Now', '立即同步'],
  cloud_storage: ['Cloud Storage', '云端存储'], refresh_storage: ['Refresh', '刷新'],
  available_storage: ['Available', '可用'], storage_files: ['files', '个文件'],
  storage_loading: ['Loading storage…', '正在获取存储信息…'], storage_unavailable: ['Storage information unavailable', '暂无法获取存储信息'],
  cloud_download: ['Download to read', '下载后阅读'], remove_cloud_book: ['Remove from cloud and device', '从云端和设备移除'],
  remove_cloud_description: ['Cloud removal also removes this book from your other Readest shelves. Readest retains the cloud files.', '从云端移除后，其他 Readest 设备的书架也将移除此书。Readest 会保留云端文件。'],
  error_invalid_cloud: ['Readest returned invalid sync data. Your local data is retained.', 'Readest 返回的同步数据无效。本地数据仍会保留。'],
  error_cloud_file_missing: ['This cloud book is not available to download. Upload the EPUB from the source device.', '此云端书籍暂不可下载，请在原设备上传 EPUB 文件。'],
  error_cloud_checksum: ['The downloaded file does not match this book. Sync again from the source device.', '下载文件与此书不匹配，请从原设备重新同步。'],
  error_cloud_conflict: ['The cloud position changed during upload. Check remote progress and choose a position.', '上传期间云端位置发生变化，请检查远端进度并选择要保留的位置。'],
  cloud_progress_pending: ['{count} saved positions need review. Open those books to choose where to continue.', '{count} 个已保存位置需要确认，请打开对应书籍并选择要继续阅读的位置。'],
  email: ['Email', '邮箱'], sign_in: ['Sign in', '登录'], sync_fonts_now: ['Sync now', '立即同步'],
  last_synced: ['Last synced', '上次同步'], never_synced: ['Not yet synced', '尚未同步'],
  decrease_value: ['Decrease', '减小'], increase_value: ['Increase', '增大'],
  error_invalid_font: ['Invalid or unsupported font. Choose a valid TTF or OTF file up to 32 MB.', '字体无效或不受支持。请选择最大 32 MB 的有效 TTF 或 OTF 文件。'],
  error_invalid_replica: ['Readest returned invalid font data. Sync will retry without skipping it.', 'Readest 返回的字体数据无效。同步将重试，不会跳过该数据。'],
  error_sync_quota: ['Your Readest storage quota is full.', '你的 Readest 存储空间已满。'],
  error_sync_clock: ['Check the device date and time, then sync again.', '请检查设备日期和时间，然后重新同步。'],
  account: ['Account', '账户'], replica_status_idle: ['Ready', '就绪'], replica_status_connected: ['Connected', '已连接'],
  replica_status_syncing: ['Syncing…', '正在同步…'], replica_status_synced: ['Synced', '已同步'],
  replica_status_pending: ['Progress needs review', '阅读进度需要确认'], replica_status_error: ['Sync needs attention', '同步需要处理']
};
for (const [locale, index] of [['base', 0], ['zh_CN', 1]]) {
  const dir = `entry/src/main/resources/${locale}/element`;
  await mkdir(dir, { recursive: true });
  await writeFile(`${dir}/string.json`, JSON.stringify({ string: Object.entries(strings).map(([name, values]) => ({ name, value: values[index] })) }, null, 2) + '\n');
}
await writeFile('AppScope/resources/base/element/string.json', JSON.stringify({ string: [{ name: 'app_name', value: 'Readest' }] }, null, 2) + '\n');
